-- MySQL Script generated by MySQL Workbench
-- Sun Dec  4 19:40:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BD_Clinica_Medica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD_Clinica_Medica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_Clinica_Medica` DEFAULT CHARACTER SET utf8 ;
USE `BD_Clinica_Medica` ;

-- -----------------------------------------------------
-- Table `BD_Clinica_Medica`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Clinica_Medica`.`Usuario` (
  `Codigo` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Clave` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NULL,
  `Rol` VARCHAR(45) NOT NULL,
  `EstaActivo` TINYINT NOT NULL,
  PRIMARY KEY (`Codigo`),
  UNIQUE INDEX `Codigo_UNIQUE` (`Codigo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Clinica_Medica`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Clinica_Medica`.`Servicio` (
  `Codigo` INT NOT NULL,
  `Descripcion` VARCHAR(50) NOT NULL,
  `Precio` DECIMAL NOT NULL,
  `FechaCreacion` DATETIME NOT NULL,
  `Imagen` LONGBLOB NULL,
  PRIMARY KEY (`Codigo`),
  UNIQUE INDEX `Codigo_UNIQUE` (`Codigo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Clinica_Medica`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Clinica_Medica`.`Paciente` (
  `IdentidadPaciente` NVARCHAR(30) NOT NULL,
  `Nombre` VARCHAR(65) NOT NULL,
  `Telefono` VARCHAR(20) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Direccion` VARCHAR(100) NULL,
  `EstadoCivil` VARCHAR(45) NOT NULL,
  `Genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdentidadPaciente`),
  UNIQUE INDEX `IdentidadPaciente_UNIQUE` (`IdentidadPaciente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Clinica_Medica`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Clinica_Medica`.`Factura` (
  `Id` INT NOT NULL,
  `IdentidadPaciente` NVARCHAR(30) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `CodigoUsuario` VARCHAR(20) NOT NULL,
  `ISV` DECIMAL(8,2) NOT NULL,
  `Descuento` DECIMAL(8,2) NOT NULL,
  `Sub total` DECIMAL(8,2) NOT NULL,
  `Total` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Factura_Usuario_idx` (`CodigoUsuario` ASC) VISIBLE,
  INDEX `fk_Factura_Paciente_idx` (`IdentidadPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Usuario`
    FOREIGN KEY (`CodigoUsuario`)
    REFERENCES `BD_Clinica_Medica`.`Usuario` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Paciente`
    FOREIGN KEY (`IdentidadPaciente`)
    REFERENCES `BD_Clinica_Medica`.`Paciente` (`IdentidadPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Clinica_Medica`.`DetalleFactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Clinica_Medica`.`DetalleFactura` (
  `id` INT NOT NULL,
  `IdFactura` INT NOT NULL,
  `CodigoServicio` INT NOT NULL,
  `Precio` DECIMAL(8,2) NULL,
  `Cantidad` INT NULL,
  `Total` DECIMAL(8,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_DetalleFactura_Servicio1_idx` (`CodigoServicio` ASC) VISIBLE,
  INDEX `fk_DetalleFactura_Factura_idx` (`IdFactura` ASC) VISIBLE,
  CONSTRAINT `fk_DetalleFactura_Servicio`
    FOREIGN KEY (`CodigoServicio`)
    REFERENCES `BD_Clinica_Medica`.`Servicio` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleFactura_Factura`
    FOREIGN KEY (`IdFactura`)
    REFERENCES `BD_Clinica_Medica`.`Factura` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
