-- MySQL Script generated by MySQL Workbench
-- Fri Dec  2 00:26:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BD_Clinica_Medica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD_Clinica_Medica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_Clinica_Medica` DEFAULT CHARACTER SET utf8 ;
USE `BD_Clinica_Medica` ;

-- -----------------------------------------------------
-- Table `BD_Clinica_Medica`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Clinica_Medica`.`Usuario` (
  `Codigo` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Clave` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NULL,
  `Rol` VARCHAR(45) NOT NULL,
  `EstaActivo` TINYINT NOT NULL,
  PRIMARY KEY (`Codigo`),
  UNIQUE INDEX `Codigo_UNIQUE` (`Codigo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Clinica_Medica`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Clinica_Medica`.`Servicio` (
  `Codigo` INT NOT NULL,
  `Descripcion` VARCHAR(50) NOT NULL,
  `Precio` DECIMAL NOT NULL,
  `FechaCreacion` DATETIME NOT NULL,
  `Imagen` LONGBLOB NULL,
  PRIMARY KEY (`Codigo`),
  UNIQUE INDEX `Codigo_UNIQUE` (`Codigo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Clinica_Medica`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Clinica_Medica`.`Paciente` (
  `IdentidadPaciente` NVARCHAR(30) NOT NULL,
  `Nombre` VARCHAR(65) NOT NULL,
  `Telefono` VARCHAR(20) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Direccion` VARCHAR(100) NULL,
  `EstadoCivil` VARCHAR(45) NOT NULL,
  `Genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdentidadPaciente`),
  UNIQUE INDEX `IdentidadPaciente_UNIQUE` (`IdentidadPaciente` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
